// Teacher read flow + optional activity create (LT_ALLOW_WRITES=1).
import http from 'k6/http';
import { check } from 'k6';
import { BASE_URL, ALLOW_WRITES, think } from '../lib/config.js';
import { authHeaders, getTagged } from '../lib/auth.js';

export function teacherFlow(token) {
  if (!token) return;
  getTagged('/api/v1/activities', token, 'activities:list', [404]);
  getTagged('/api/v1/activities/teacher/dashboard', token, 'teacher/dashboard', [404]);
  getTagged('/api/v1/classrooms', token, 'classrooms:list', [404]);
  getTagged('/api/v1/standards', token, 'standards:list', [404]);

  if (ALLOW_WRITES) {
    const params = authHeaders(token);
    params.tags = { name: 'activities:create' };
    const res = http.post(
      `${BASE_URL}/api/v1/activities`,
      JSON.stringify({
        title: `LoadTest Activity ${__VU}-${Date.now()}`,
        description: 'Auto-generated by k6 load test — safe to delete.',
        bloom_level: 'remember',
        location_info: { lat: 47.6062, lng: -122.3321, radius_meters: 100 },
      }),
      params,
    );
    check(res, { 'create activity -> 2xx/4xx': (r) => r.status < 500 });
  }

  think(2, 5);
}
