# alembic.ini

[alembic]
script_location = alembic

[loggers]
keys = root,sqlalchemy

[handlers_disabled]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy_disabled]
level = WARN
handlers =

[handler_console]
class = StreamHandler
args = (sys.stderr,)
format = %(levelname)s [%(name)s] %(message)s

[formatter_generic]
format = %(levelname)s [%(asctime)s] %(name)s - %(message)s
datefmt = %H:%M:%S

[sqlalchemy]
sqlalchemy.url = postgresql://postgres:SecurePassword123@localhost:5432/peripateticware

