"""initial_schema

Revision ID: 84daf034be09
Revises: 
Create Date: 2026-05-23 20:26:27.808899

"""
from typing import Sequence, Union

from alembic import op
from pgvector.sqlalchemy import Vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84daf034be09'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('grade_level', sa.Integer(), nullable=True),
    sa.Column('bloom_level', sa.Integer(), nullable=True),
    sa.Column('marzano_level', sa.Integer(), nullable=True),
    sa.Column('content_embedding', Vector(dim=384), nullable=True),
    sa.Column('raw_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_units_subject'), 'curriculum_units', ['subject'], unique=False)
    op.create_index(op.f('ix_curriculum_units_title'), 'curriculum_units', ['title'], unique=False)
    op.create_table('location_contexts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('wikipedia_articles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('wikidata_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('geographic_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('educational_summary', sa.Text(), nullable=True),
    sa.Column('cache_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_location_contexts_lat_lng', 'location_contexts', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_location_contexts_latitude'), 'location_contexts', ['latitude'], unique=False)
    op.create_index('ix_location_contexts_location_name', 'location_contexts', ['location_name'], unique=False)
    op.create_index(op.f('ix_location_contexts_longitude'), 'location_contexts', ['longitude'], unique=False)
    op.create_table('observability_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('total_latency_ms', sa.Integer(), nullable=True),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observability_logs_created_at'), 'observability_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_observability_logs_request_id'), 'observability_logs', ['request_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', 'PARENT', 'ADMIN', name='userrole'), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('learning_objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('location_latitude', sa.Float(), nullable=False),
    sa.Column('location_longitude', sa.Float(), nullable=False),
    sa.Column('location_radius_meters', sa.Integer(), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('grade_level', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('materials_needed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('curriculum_unit_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('bloom_level', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.Enum('INQUIRY', 'DISCUSSION', 'HANDS_ON', 'VIRTUAL', 'HYBRID', name='activitytype'), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='activitystatus'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_shareable', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_created_at'), 'activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_activities_status'), 'activities', ['status'], unique=False)
    op.create_index(op.f('ix_activities_subject'), 'activities', ['subject'], unique=False)
    op.create_index(op.f('ix_activities_teacher_id'), 'activities', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_activities_title'), 'activities', ['title'], unique=False)
    op.create_table('assessment_rubrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('framework', sa.Enum('BLOOMS', 'MARZANO', 'DOK', 'SOLO', 'CUSTOM', name='assessmentframework'), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_rubrics_created_at'), 'assessment_rubrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_assessment_rubrics_teacher_id'), 'assessment_rubrics', ['teacher_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('grade_level', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PLANNING', 'ACTIVE', 'COMPLETED', 'ARCHIVED', name='projectstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_created_at'), 'projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_subject'), 'projects', ['subject'], unique=False)
    op.create_index(op.f('ix_projects_teacher_id'), 'projects', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    op.create_table('student_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('learning_style', sa.String(length=50), nullable=True),
    sa.Column('bloom_level', sa.Integer(), nullable=True),
    sa.Column('marzano_level', sa.Integer(), nullable=True),
    sa.Column('prior_knowledge', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('device_sensor_precision', sa.Float(), nullable=True),
    sa.Column('device_npu_power', sa.Float(), nullable=True),
    sa.Column('device_camera_level', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_curriculum',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('curriculum_unit_id', sa.UUID(), nullable=False),
    sa.Column('alignment_strength', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['curriculum_unit_id'], ['curriculum_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_curriculum_activity_id', 'activity_curriculum', ['activity_id'], unique=False)
    op.create_index('ix_activity_curriculum_curriculum_id', 'activity_curriculum', ['curriculum_unit_id'], unique=False)
    op.create_index(op.f('ix_activity_curriculum_curriculum_unit_id'), 'activity_curriculum', ['curriculum_unit_id'], unique=False)
    op.create_table('learning_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('curriculum_id', sa.UUID(), nullable=True),
    sa.Column('activity_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('inquiry_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum_units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('activity_id', sa.UUID(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_activities_activity_id'), 'project_activities', ['activity_id'], unique=False)
    op.create_index(op.f('ix_project_activities_project_id'), 'project_activities', ['project_id'], unique=False)
    op.create_table('multimodal_inputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('input_type', sa.String(length=50), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', Vector(dim=384), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('processing_latency_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('operation', sa.String(length=50), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=True),
    sa.Column('sync_attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_logs_created_at'), 'sync_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_sync_logs_device_id'), 'sync_logs', ['device_id'], unique=False)
    op.create_table('triple_join_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('site_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('curriculum_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('persona_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('inquiry_path', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_resources', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('triple_join_records')
    op.drop_index(op.f('ix_sync_logs_device_id'), table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_created_at'), table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_table('multimodal_inputs')
    op.drop_index(op.f('ix_project_activities_project_id'), table_name='project_activities')
    op.drop_index(op.f('ix_project_activities_activity_id'), table_name='project_activities')
    op.drop_table('project_activities')
    op.drop_table('learning_sessions')
    op.drop_index(op.f('ix_activity_curriculum_curriculum_unit_id'), table_name='activity_curriculum')
    op.drop_index('ix_activity_curriculum_curriculum_id', table_name='activity_curriculum')
    op.drop_index('ix_activity_curriculum_activity_id', table_name='activity_curriculum')
    op.drop_table('activity_curriculum')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.drop_index(op.f('ix_projects_teacher_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_subject'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_at'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_assessment_rubrics_teacher_id'), table_name='assessment_rubrics')
    op.drop_index(op.f('ix_assessment_rubrics_created_at'), table_name='assessment_rubrics')
    op.drop_table('assessment_rubrics')
    op.drop_index(op.f('ix_activities_title'), table_name='activities')
    op.drop_index(op.f('ix_activities_teacher_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_subject'), table_name='activities')
    op.drop_index(op.f('ix_activities_status'), table_name='activities')
    op.drop_index(op.f('ix_activities_created_at'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_observability_logs_request_id'), table_name='observability_logs')
    op.drop_index(op.f('ix_observability_logs_created_at'), table_name='observability_logs')
    op.drop_table('observability_logs')
    op.drop_index(op.f('ix_location_contexts_longitude'), table_name='location_contexts')
    op.drop_index('ix_location_contexts_location_name', table_name='location_contexts')
    op.drop_index(op.f('ix_location_contexts_latitude'), table_name='location_contexts')
    op.drop_index('ix_location_contexts_lat_lng', table_name='location_contexts')
    op.drop_table('location_contexts')
    op.drop_index(op.f('ix_curriculum_units_title'), table_name='curriculum_units')
    op.drop_index(op.f('ix_curriculum_units_subject'), table_name='curriculum_units')
    op.drop_table('curriculum_units')
    # ### end Alembic commands ###


